# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subject.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 553)
        Dialog.setMinimumSize(QtCore.QSize(716, 553))
        Dialog.setMaximumSize(QtCore.QSize(716, 553))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditHours = QtWidgets.QLineEdit(Dialog)
        self.lineEditHours.setObjectName("lineEditHours")
        self.gridLayout.addWidget(self.lineEditHours, 0, 4, 1, 1)
        self.lblDesc = QtWidgets.QLabel(Dialog)
        self.lblDesc.setObjectName("lblDesc")
        self.gridLayout.addWidget(self.lblDesc, 1, 3, 1, 1)
        self.lblHours = QtWidgets.QLabel(Dialog)
        self.lblHours.setObjectName("lblHours")
        self.gridLayout.addWidget(self.lblHours, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioWithTest = QtWidgets.QRadioButton(self.groupBox)
        self.radioWithTest.setObjectName("radioWithTest")
        self.horizontalLayout_3.addWidget(self.radioWithTest)
        self.radioWithoutTest = QtWidgets.QRadioButton(self.groupBox)
        self.radioWithoutTest.setObjectName("radioWithoutTest")
        self.horizontalLayout_3.addWidget(self.radioWithoutTest)
        self.gridLayout.addWidget(self.groupBox, 2, 3, 1, 2)
        self.lblName = QtWidgets.QLabel(Dialog)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(Dialog)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 0, 1, 1, 1)
        self.lineEditCode = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode.setObjectName("lineEditCode")
        self.gridLayout.addWidget(self.lineEditCode, 1, 1, 1, 1)
        self.lblCode = QtWidgets.QLabel(Dialog)
        self.lblCode.setObjectName("lblCode")
        self.gridLayout.addWidget(self.lblCode, 1, 0, 1, 1)
        self.lineEditDescription = QtWidgets.QLineEdit(Dialog)
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.gridLayout.addWidget(self.lineEditDescription, 1, 4, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 30, 261, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioA = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioA.setObjectName("radioA")
        self.horizontalLayout_2.addWidget(self.radioA)
        self.radioB = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioB.setObjectName("radioB")
        self.horizontalLayout_2.addWidget(self.radioB)
        self.radioC = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioC.setObjectName("radioC")
        self.horizontalLayout_2.addWidget(self.radioC)
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.treeSchedule = QtWidgets.QTreeView(Dialog)
        self.treeSchedule.setObjectName("treeSchedule")
        self.verticalLayout.addWidget(self.treeSchedule)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFinish = QtWidgets.QPushButton(Dialog)
        self.btnFinish.setObjectName("btnFinish")
        self.horizontalLayout.addWidget(self.btnFinish)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Subject"))
        self.lblDesc.setText(_translate("Dialog", "Beschreibung"))
        self.lblHours.setText(_translate("Dialog", "Anzahl"))
        self.groupBox.setTitle(_translate("Dialog", "Überprüfung"))
        self.radioWithTest.setText(_translate("Dialog", "Mit"))
        self.radioWithoutTest.setText(_translate("Dialog", "Ohne"))
        self.lblName.setText(_translate("Dialog", "Name"))
        self.lblCode.setText(_translate("Dialog", "Code"))
        self.groupBox_2.setTitle(_translate("Dialog", "Kursart"))
        self.radioA.setText(_translate("Dialog", "A"))
        self.radioB.setText(_translate("Dialog", "B"))
        self.radioC.setText(_translate("Dialog", "C"))
        self.btnFinish.setText(_translate("Dialog", "Fertig"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
